Resources:
  DeepAgentCognitoDeepAgentCognitoUserPoolC980B682:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: The verification code to your new account is {####}
      EmailVerificationSubject: Verify your new account
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Mutable: true
          Name: email
          Required: true
      SmsVerificationMessage: The verification code to your new account is {####}
      UserPoolName: DeepAgentCognitoUserPool
      UsernameAttributes:
        - email
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: The verification code to your new account is {####}
        EmailSubject: Verify your new account
        SmsMessage: The verification code to your new account is {####}
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: agent-core-deep-agent-dev/DeepAgentCognito/DeepAgentCognitoUserPool/Resource
  DeepAgentCognitoDeepAgentCognitoUserPoolDeepAgentCognitoUserPoolDomainDB0EA967:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain:
        Fn::Join:
          - "-"
          - - deep-agent
            - Ref: AWS::AccountId
            - Ref: AWS::Region
      UserPoolId:
        Ref: DeepAgentCognitoDeepAgentCognitoUserPoolC980B682
    Metadata:
      aws:cdk:path: agent-core-deep-agent-dev/DeepAgentCognito/DeepAgentCognitoUserPool/DeepAgentCognitoUserPoolDomain/Resource
  DeepAgentCognitoDeepAgentCognitoUserPoolDeepAgentCognitoResourceServer02BE1B7E:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      Identifier: deepagent
      Name: deepagent
      Scopes:
        - ScopeDescription: Invoke the deep agent
          ScopeName: invoke
      UserPoolId:
        Ref: DeepAgentCognitoDeepAgentCognitoUserPoolC980B682
    Metadata:
      aws:cdk:path: agent-core-deep-agent-dev/DeepAgentCognito/DeepAgentCognitoUserPool/DeepAgentCognitoResourceServer/Resource
  DeepAgentCognitoDeepAgentCognitoUserPoolDeepAgentCognitoUserPoolClient3365974C:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      AccessTokenValidity: 60
      AllowedOAuthFlows:
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - openid
        - email
        - profile
        - Fn::Join:
            - ""
            - - Ref: DeepAgentCognitoDeepAgentCognitoUserPoolDeepAgentCognitoResourceServer02BE1B7E
              - /invoke
      CallbackURLs:
        - https://example.com
      ClientName: DeepAgentCognitoUserPoolClient
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      GenerateSecret: false
      IdTokenValidity: 60
      PreventUserExistenceErrors: ENABLED
      RefreshTokenValidity: 43200
      SupportedIdentityProviders:
        - COGNITO
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: minutes
      UserPoolId:
        Ref: DeepAgentCognitoDeepAgentCognitoUserPoolC980B682
    Metadata:
      aws:cdk:path: agent-core-deep-agent-dev/DeepAgentCognito/DeepAgentCognitoUserPool/DeepAgentCognitoUserPoolClient/Resource
  DeepAgentCoreDeepAgentCoreAgtcoreRoleE5754266:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: bedrock-agentcore.amazonaws.com
        Version: "2012-10-17"
      Description: IAM role for Bedrock AgentCore Runtime
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - ecr:BatchGetImage
                  - ecr:GetDownloadUrlForLayer
                Effect: Allow
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:ecr:us-east-1:"
                      - Ref: AWS::AccountId
                      - :repository/*
                Sid: ECRImageAccess
              - Action:
                  - logs:CreateLogGroup
                  - logs:DescribeLogStreams
                Effect: Allow
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:logs:us-east-1:"
                      - Ref: AWS::AccountId
                      - :log-group:/aws/bedrock-agentcore/runtimes/*
              - Action: logs:DescribeLogGroups
                Effect: Allow
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:logs:us-east-1:"
                      - Ref: AWS::AccountId
                      - :log-group:*
              - Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource:
                  Fn::Join:
                    - ""
                    - - "arn:aws:logs:us-east-1:"
                      - Ref: AWS::AccountId
                      - :log-group:/aws/bedrock-agentcore/runtimes/*:log-stream:*
              - Action: ecr:GetAuthorizationToken
                Effect: Allow
                Resource: "*"
                Sid: ECRTokenAccess
              - Action:
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                  - xray:PutTelemetryRecords
                  - xray:PutTraceSegments
                Effect: Allow
                Resource: "*"
              - Action: cloudwatch:PutMetricData
                Condition:
                  StringEquals:
                    cloudwatch:namespace: bedrock-agentcore
                Effect: Allow
                Resource: "*"
              - Action:
                  - bedrock-agentcore:GetWorkloadAccessToken
                  - bedrock-agentcore:GetWorkloadAccessTokenForJWT
                  - bedrock-agentcore:GetWorkloadAccessTokenForUserId
                Effect: Allow
                Resource:
                  - Fn::Join:
                      - ""
                      - - "arn:aws:bedrock-agentcore:us-east-1:"
                        - Ref: AWS::AccountId
                        - :workload-identity-directory/default
                  - Fn::Join:
                      - ""
                      - - "arn:aws:bedrock-agentcore:us-east-1:"
                        - Ref: AWS::AccountId
                        - :workload-identity-directory/default/workload-identity/agentName-*
                Sid: GetAgentAccessToken
              - Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Effect: Allow
                Resource:
                  - arn:aws:bedrock:*::foundation-model/*
                  - Fn::Join:
                      - ""
                      - - "arn:aws:bedrock:us-east-1:"
                        - Ref: AWS::AccountId
                        - :*
                Sid: BedrockModelInvocation
            Version: "2012-10-17"
          PolicyName: RuntimeAccessPolicy
    Metadata:
      aws:cdk:path: agent-core-deep-agent-dev/DeepAgentCore/DeepAgentCoreAgtcoreRole/Resource
  DeepAgentCoreDeepAgentCoreAgentRuntime55FE1A7E:
    Type: AWS::BedrockAgentCore::Runtime
    Properties:
      AgentRuntimeArtifact:
        ContainerConfiguration:
          ContainerUri:
            Fn::Sub: ${AWS::AccountId}.dkr.ecr.us-east-1.${AWS::URLSuffix}/cdk-hnb659fds-container-assets-${AWS::AccountId}-us-east-1:42154b144ab1b62b505b1c9dec7daf8103c4891017178c9a140583423e24cc77
      AgentRuntimeName: DeepAgentCoreAgentRuntime
      EnvironmentVariables:
        AWS_REGION: us-east-1
      NetworkConfiguration:
        NetworkMode: PUBLIC
      ProtocolConfiguration: HTTP
      RoleArn:
        Fn::GetAtt:
          - DeepAgentCoreDeepAgentCoreAgtcoreRoleE5754266
          - Arn
    Metadata:
      aws:cdk:path: agent-core-deep-agent-dev/DeepAgentCore/DeepAgentCoreAgentRuntime
  DeepAgentCoreDeepAgentCoreAgentRuntimeEndpointEABE2989:
    Type: AWS::BedrockAgentCore::RuntimeEndpoint
    Properties:
      AgentRuntimeId:
        Fn::GetAtt:
          - DeepAgentCoreDeepAgentCoreAgentRuntime55FE1A7E
          - AgentRuntimeId
      AgentRuntimeVersion: "1"
      Name: dev
    Metadata:
      aws:cdk:path: agent-core-deep-agent-dev/DeepAgentCore/DeepAgentCoreAgentRuntimeEndpoint
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/12NwU7DQAxEv6X3jYGEH4CWAyeqRJyr7cYEk8SOdh2qarX/jpY0KOLk8ZvxuITysYL7nb2EwrV9MdAZYqPW9cZewik66ZhUIL4H9EeRwew/+E+v4iCjJd5aN7KuNQaZvcMG/Tf6bfCfs+L9QMi6DS4kGXT+ZENADXAQ16N/HW2HT5lkD2qcJJCKvz7bgIbsCLGWAXNXnsmcsfXietshqxOPELM1s9K4pBb5wu0kxJpShm+zTrOa3z+N2o64S+Z41U/huwoeKih3X4Go8Msx3Ep+AI2dGX1gAQAA
    Metadata:
      aws:cdk:path: agent-core-deep-agent-dev/CDKMetadata/Default
Outputs:
  DeepAgentCognitoDeepAgentCognitoUserPoolId21D35626:
    Description: Cognito User Pool ID
    Value:
      Ref: DeepAgentCognitoDeepAgentCognitoUserPoolC980B682
    Export:
      Name: DeepAgentCognitoUserPoolId
  DeepAgentCognitoDeepAgentCognitoUserPoolArn79B3333E:
    Description: Cognito User Pool ARN
    Value:
      Fn::GetAtt:
        - DeepAgentCognitoDeepAgentCognitoUserPoolC980B682
        - Arn
    Export:
      Name: DeepAgentCognitoUserPoolArn
  DeepAgentCognitoDeepAgentCognitoUserPoolClientId28C193CB:
    Description: Cognito User Pool Client ID
    Value:
      Ref: DeepAgentCognitoDeepAgentCognitoUserPoolDeepAgentCognitoUserPoolClient3365974C
    Export:
      Name: DeepAgentCognitoUserPoolClientId
  DeepAgentCognitoDeepAgentCognitoUserPoolDomainNameE1A762FA:
    Description: Cognito User Pool Domain name
    Value:
      Ref: DeepAgentCognitoDeepAgentCognitoUserPoolDeepAgentCognitoUserPoolDomainDB0EA967
    Export:
      Name: DeepAgentCognitoUserPoolDomainName
  DeepAgentCognitoDeepAgentCognitoUserPoolDomainBaseUrl5602F766:
    Description: Cognito User Pool Domain base URL
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: DeepAgentCognitoDeepAgentCognitoUserPoolDeepAgentCognitoUserPoolDomainDB0EA967
          - .auth.us-east-1.amazoncognito.com
    Export:
      Name: DeepAgentCognitoUserPoolDomainBaseUrl
  DeepAgentCognitoDeepAgentCognitoResourceServerIdentifier71137B9F:
    Description: Cognito Resource Server identifier
    Value:
      Ref: DeepAgentCognitoDeepAgentCognitoUserPoolDeepAgentCognitoResourceServer02BE1B7E
    Export:
      Name: DeepAgentCognitoResourceServerIdentifier
  DeepAgentCoreDeepAgentCoreDockerAssetImageUriC19AD2EA:
    Description: Docker asset image URI
    Value:
      Fn::Sub: ${AWS::AccountId}.dkr.ecr.us-east-1.${AWS::URLSuffix}/cdk-hnb659fds-container-assets-${AWS::AccountId}-us-east-1:42154b144ab1b62b505b1c9dec7daf8103c4891017178c9a140583423e24cc77
    Export:
      Name: DeepAgentCoreDockerAssetImageUri
  DeepAgentCoreDeepAgentCoreAgentRuntimeId91875D8E:
    Description: Agent runtime ID
    Value:
      Fn::GetAtt:
        - DeepAgentCoreDeepAgentCoreAgentRuntime55FE1A7E
        - AgentRuntimeId
    Export:
      Name: DeepAgentCoreAgentRuntimeId
  DeepAgentCoreDeepAgentCoreAgentRuntimeArnA3D7DB57:
    Description: Agent runtime ARN
    Value:
      Fn::GetAtt:
        - DeepAgentCoreDeepAgentCoreAgentRuntime55FE1A7E
        - AgentRuntimeArn
    Export:
      Name: DeepAgentCoreAgentRuntimeArn
  DeepAgentCoreDeepAgentCoreAgtcoreRoleArnC5209B78:
    Description: Agent Runtime role ARN
    Value:
      Fn::GetAtt:
        - DeepAgentCoreDeepAgentCoreAgtcoreRoleE5754266
        - Arn
    Export:
      Name: DeepAgentCoreAgtcoreRoleArn
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
